#!/bin/bash
branchName=`git rev-parse --abbrev-ref HEAD`
echo $branchName

read -r branchType issueId description <<<$(echo $branchName | sed -nE 's/(.*)\/(.*)\/(.*)/\1 \2 \3/p')

if [ -z "$issueId" ]; then
  exit 0
fi

sed -i.bak -e "1s/^/\[$issueId\]: /" $1
